### ISSUE TITLE
ACL requires "site.login" even if "admin.login" allowed

### ISSUE THREAD

**Issue by matthew-dean** [getgrav/grav-plugin-login#105]
I think this is probably a side effect of only having a single login route, but having two different user sessions for site and admin (which is kind of bizarre).

Basically - if
1. a user can login as an admin but not as a "site user", 
2. a page allows both admin and site users, 
3. a user not logged in as an admin...

...then, that user can never really access a login-protected page, even though admin users can access it. I believe what happens is that the login form provided by the login plugin only attempts to log that user in as a "site" user with a site session, and there's only one login form redirect. Therefore, even though the user CAN access the page in theory, as an admin, there's no "redirect behavior" that can successfully log in an admin user to the admin session (or if it does, that can also log in site users to the site session).

Expected behavior - a user that's "logged in" is "logged in", full stop, and simply has "site" or "admin" roles. This is why this is the typical authentication design strategy. You run into too many edge cases of having to duplicate functionality, or a user having a simultaneous "logged in" and "logged out" status. As it stands, there are four states of logged in / logged out which have to be checked. (Logged out admin/logged out site, logged in admin/logged out site, logged out admin/logged in site, logged in admin/logged in site). This is an unnecessarily complicated authentication flow.

That's all besides the point of this issue, which is just that because of this design, redirecting to a login page doesn't really work for specific users.

**Comment by flaviocopes** [comment]
Currently the frontend user authentication/login is tied to `site.login`. 

That's a convention. The Login plugin checks for that permission, otherwise you cannot login to the frontend. If you want to login to the frontend, your user needs to have `site.login`.

Having separate sessions for admin and site is a design decision. IMHO convenient, as you can login as a user in the admin, and login as another user in the front, or check how the site looks for non-logged in users without having to logout from Admin. And, have different session timeouts.
