### ISSUE TITLE
Inconsistent form/page generation

### ISSUE THREAD

**Issue by Salvatos** [getgrav/grav-plugin-login#110]
How come the Register page uses a completely different layout (based on the form template) and not its own twig like every other function of this plugin? I had to manually remove the twig templating from `addRegisterPage()` in login.php, which I'll have to redo every time it's updated, and create the twig templates myself so the forms would have the same style.

Is there a security concern that justifies this discrepancy?

**Comment by rhukster** [comment]
There is some inconsistency but it mainly is due to the fact that registration is a flexible page that can be customized.  The other pages (login/forgot/reset) etc are, all sort of related to the login (small login box).  

You don't have to edit the plugin, you can simply provide a custom form.html.twig in your theme that will handle this standard form output in a way that fits your design better.  The same goes for the other twig files actually (login.php included). You can simply provide a version in your theme to override the one in the plugin.

**Comment by Salvatos** [comment]
I had no idea plugin-specific php files could be added to themes. Where should I put my modified login.php so that it overrides the plugin's version?

**Comment by flaviocopes** [comment]
You cannot override php files, but Twig files included by the plugin can be overwritten by the ones you put in your theme.

**Comment by Salvatos** [comment]
Thanks, that's what I thought. My Register twig won't get called at all without a modified login.php because the plugin specifies the 'form' template for that page instead (`$page->template('form');`).
