### ISSUE TITLE
Any user with site access can access protected page media

### ISSUE THREAD

**Issue by codesplain** [getgrav/grav-plugin-login#132]
Hi there,

Came across some undesirable behaviour in a certain scenario with the following config:

```yaml
protect_protected_page_media: true
parent_acl: true
```
## Scenario

- `user1` & `user2` both have site access
- `/restricted` has defined that only `user1` can access the page
- `user1` can access `/restricted`
- if `user2` tries to access `/restricted`, they will see the contents of `unauthorized.md` *(as expected)*
- if `user2` tries to access media files, e.g. `/restricted/media.jpg`, they can see them *(undesirable)*

> Note: if a guest user tries to access `/resticted/media.jpg`, they will be redirected to a login page as expected.

So any user with site access will be able to access media files of a protected page, regardless of that protected page excluding certain users based on a group e.g. whether they have paid.

Did a quick fix locally by doing a 302 redirect if the uri extension is a media type, near the end of `setUnauthorizedPage()` https://github.com/getgrav/grav-plugin-login/blob/3f9560ad146cd231a9acca6b541ef8130c9c2d70/login.php#L415-L434

Wanted to see whether there was a better way of doing this?

**Comment by rhukster** [comment]
can you create a pull request so i can easily test this?  Cheers.

**Comment by rhukster** [comment]
This actually turned out to be a bigger problem.  You can't redirect non-HTML requests to HTML pages, so moved this up into `authorizePage()` and simply throw an `403` error if unauthorized.

https://github.com/getgrav/grav-plugin-login/commit/4e6199e7bfe383efd5e7e10fc59355cd1f30677a

Also this uncovered an issue with page's that were not found under protected pages.  That's fixed in Grav develop branch.

https://github.com/getgrav/grav/commit/a4ab5d9106e83438f64eb84919b14d20013ab9b2

Please test if possible :)

**Comment by codesplain** [comment]
Cheers - tested the latest release & works as expected 👍
