### ISSUE TITLE
remove register link after registering

### ISSUE THREAD

**Issue by cesarmarinhorj** [getgrav/grav-plugin-login#143]
After a successfull register, the link to register could be removed.

**Comment by rhukster** [comment]
Which register link are you referring to?

**Comment by XizzoR** [comment]
Hi!

Don't know if this is a good idea, to continue writing on this issue instead of asking a question in the other one, but let say I made custom registration page. Of course, that page is accessible through menu (like any other visible page). I know that `dynamic_page_visibility` option can hide pages when user is 
not logged in, but what about doing vice versa for the registration page? I mean hide the page (Registraion page i.e.) when user is logged in.

**Comment by XizzoR** [comment]
Never mind my post, I found the way to hide pages when user IS logged on. The trick is simple: make a page you want to hide and set `visible` to `disabled`. Now, add custom menu item (define it in your theme, but first enable custom menu items to be rendered) with url set to your page. Then (the hardest part, if I might say so) find the html.twig file responsible for rendering a navigation bar in your theme. For me, it is `user\themes\quark-open-publishing\templates\partials\navigation.html.twig`. Now open it and find list element (the <ul> one) and put IF statement that will surround a list item (the <li> element). The statement should say if user is not logged in, proceed with rendering an html element. For me, it is `if grav.user.authorize('site.login') == false` (Note: I'm using Login plugin for authenticating an user). Of course, this will hide every custom menu item from site visitor, so if you are not using custom menu items feature just for this purpose, the IF statement should be modified to your needs.

I hope this noob friendly guide will help anyone.

P.S. If you want to hide page when user IS NOT logged in, just turn `false` to `true` in IF statement.

**Comment by rhukster** [comment]
Also please see my comment here:

https://github.com/getgrav/grav-plugin-login/issues/179
