### ISSUE TITLE
It is safe to commit the password?

### ISSUE THREAD

**Issue by gagarine** [getgrav/grav-plugin-login#16]
Right now their is no gitignore for the account's config file. That mean it's very easy to commit them by mistake and publicly publish password (encrypted) and account information.

I didn't check your code but I guess you are using strong encryption that is hard to break (not like md5) so it's should not be a problem. But still, I'm not sure it's a good idea to let peoples commit those files by default. Do you feel comfortable with that?

If you feel comfortable to commit those files, I think a short comment in the file explaining it's not a risk to commit those file would be a nice helper. Otherwise adding a gitignore in the account folder to exclude account config is the way to go.

(I'm very new to grav)

**Comment by flaviocopes** [comment]
I think you need to think twice prior to publishing your site source code in the public, and add that to your own .gitignore.

For example the https://github.com/getgrav/grav-learn/ repository excludes the accounts folder.

It's not ignored by default because Grav is perfect for a Git-powered deploy like explained in http://getgrav.org/blog/developing-with-github-part-2, and ignoring by default would require more work on that part. 

I think the most common scenario is #2, where you host your site on a private repository, rather than publishing the entire source code of your site publicly.

**Comment by gagarine** [comment]
Ok, I understand the usecase better.

For my point of view I should be able to do a "git add ." on any project and be on the safe side. It's easy if needed to do a "git add -f" to files than are in the .gitignore if really I want to commit them. I used a lot git as a deployment tools before switching to capistrano and then ansible. But I never committed files with passwords. Peoples do that?

Perhaps user password can be on an other file like "passwd" so you can commit user's informations without their password.

**Comment by rhukster** [comment]
I don't think we're going to just change how accounts work as a solution to this one use case.  The recommended approach is to ignore the accounts folder and sync that manually as needed.

**Comment by gagarine** [comment]
Then I think the safe side is to add that in the standard gitignore and let people remove it if they want. Safety first.

**Comment by rhukster** [comment]
Done

**Comment by gagarine** [comment]
Thanks!
