### ISSUE TITLE
After password reset, redirection to 404

### ISSUE THREAD

**Issue by sebastianbaumann** [getgrav/grav-plugin-login#174]
- Open password reset link from email
- Enter new password in form
- submit form
- page redirects to "example.de/de/reset_password" which results in 404

How can I change the redirect URL for the password reset form?

**Comment by DebuggeR94** [comment]
I haw the same problem (on Grav 1.5.1, Login 2.7.3).

**Comment by ChrisGitIt** [comment]
Hi everybody,

looks like this is not working due to the missing route dispatch if there is no user/token within the url. I'm thinking about just adding a config route like "route_reset_success" that can point to a user generated "Success" page. Of course, the redirect to this route needs to be changed if the password reset is a success.

But before i start changing the source code: Are there any other solutions out there?

Greets,

Chris

**Comment by bobbwal** [comment]
I'm having a similar problem but my email link goes straight to 404. Not sure what to try next.
