### ISSUE TITLE
Disabling Forgot button. Wrong frontmatter reference?

### ISSUE THREAD

**Issue by pamtbaau** [getgrav/grav-plugin-login#230]
In template `templates/partials/login-form.html.twig` there is an if-statement that checks if the 'Forgot' button should be shown.
```
{% if page.header.form.login.forgot_button ?? true %}
```

However, this should probably be:
```
{% if page.header.forms.login.forgot_button ?? true %} 
                      ^-- note the plural of "form"
```

**Comment by mahagr** [comment]
It should actually be `page.forms().login.forgot_button` to get the normalized version of the form.

**Comment by pamtbaau** [comment]
Would you mind explaining what "_the normalized version of the form_" is?

**Comment by mahagr** [comment]
@pamtbaau You can define forms in multiple different ways, for example, if you have a single form, you can just use `page.header.form` in the blueprints, which is likely the reason why it was written in that way. In addition, there are a few more things that you can write in more than one way. The method just normalizes the array so that it always looks the same.

**Comment by pamtbaau** [comment]
@mahagr, Ah ok, makes sense... Thank you.
