### ISSUE TITLE
LDAP Support

### ISSUE THREAD

**Issue by bnason** [getgrav/grav-plugin-login#24]
Is there any current support or planned future support for LDAP Auth? If it's in the plans, has anything been written down about how it may function so I could potentially develop it?

**Comment by rhukster** [comment]
We have recently introduced OAuth support for a variety of services as this is the modern approach to single sign on.  LDAP could also be supported, but you are the first to request it.  If you would like to take a stab at adding support for LDAP, feel free to submit a Pull Request.

**Comment by khanduras** [comment]
I was the first to request it on the GetGrav.org Muut forum. 

http://getgrav.org/forum#!/plugin-development:request-ldap-authenitcati

**Comment by Vivalldi** [comment]
I'm thinking LDAP should be a separate plugin. It may need to require the login plugin but I doubt it as user authentication is going to be slightly different (and  a separate plugin can still read account files)

**Comment by flaviocopes** [comment]
We're separating OAuth authentication to a separate plugin, so also LDAP should use this way, be a separate plugin. Closing now.

**Comment by hi-ko** [comment]
+1 for a separate LDAP plugin supporting the login plugin. Ldap couln't be seen as replacement for OAuth (and vice versa). There may be a solution to use ldap behind OAuth but if you already have a common user base in ldap it would be much easier to just use it instead of fighting with the missing bits in OAuth: [What is missing in OAuth 2.0](http://ldapwiki.com/wiki/What%20is%20missing%20in%20OAuth%202.0)
