### ISSUE TITLE
emails are sent without subject lines

### ISSUE THREAD

**Issue by skinofthesoul** [getgrav/grav-plugin-login#299]
I have enabled activation and welcome emails. These get sent alright, but the subject line is always empty. I noticed that in both templates, the subject gets set like this:

    {%- set subject = 'PLUGIN_LOGIN.ACTIVATION_EMAIL_SUBJECT'|t(site_name) %}
    {%- do email.message.setSubject(subject) %}

So there's a hyphen at the opening bracket sequence, but not at the closing end. The rest of the template has the hyphen on both ends. I tried changing that, but it made no difference.

I also tried entering the subject text directly, just to see if it might be a translation issue, but that didn't work either.

Other changes I make in the templates turn up alright (I copied it into my theme), and changes in the email body in a language override file also show up. What could be the issue here?

**Comment by skinofthesoul** [comment]
I can now add that the subject line is also missing for password recovery emails, _BUT_ not if I request them via the Admin login page instead of the site login page.

**Comment by matt-j-m** [comment]
I'm experiencing the same issue with all login related emails since updating the following plugins:
- admin 1.10.41.2 to 1.10.42
- email 3.2.0 to 4.0.2
- form 7.1.3 to 7.2.1
- login 3.7.4 to 3.7.5

Emails for activations, notifications and password reset all had a subject previously, after update the subject field is empty. @skinofthesoul that bit of code in your first email is present in the older version (which I can confirm was working), so I don't think it's related to that specifically.

Thinking it was a problem with the recent update to the email plugin, I tested a simple form to send email per https://github.com/getgrav/grav-plugin-email#emails-sent-with-forms and found that subject via form does work as expected. So it seems to be relating to login generated emails specifically.

**Comment by rhukster** [comment]
Was a backwards compatibility issue in Email 4.0.. fixed in 4.0.3

**Comment by matt-j-m** [comment]
Thank you @rhukster I can confirm working on email 4.0.3 and login 3.7.6. Cheers.
