### ISSUE TITLE
Set user redirection in the user profile

### ISSUE THREAD

**Issue by laurensvanochten** [getgrav/grav-plugin-login#35]
In order to differentiate between users more easily and serve them more targeted content it would be a great feature to specify the page to which a user is redirected in the user's account.yaml file, which would overwrite the default route set in the login.yaml

**Comment by Vivalldi** [comment]
what type of redirect would you go to? I'm not seeing a use case for this but it could probably be done (we're restructuring some aspects of the plugin right now)

**Comment by laurensvanochten** [comment]
Let's assume the situation of a dashboard or smth, that will differ for different accounts. 

you could redirect user 1 to /user1dashboard, set the permission for that page to user 1 only. 

for user 2 you would redirect to user2dashboard, set permission for that page to user2 only.

Currently you need to set it in the login.yaml, meaning both user1 & user2 would be redirected to whatever you set in there. 

By using the same logic as for the template files (first check user.yaml for redirect, if not set use the redirect from login.yaml) would be a nice addition in my opinion.

**Comment by flaviocopes** [comment]
This could be done by checking if the user yaml file has a `redirect_after_login` property (or similarly named property). It's doable, just check if such property is there and redirect accordingly. Can also interact with groups, picking the property on the group if it's not set on the user.

We cannot yet add an option to the Admin plugin because Plugins cannot (yet) extend the core user/account.yaml file.
