### ISSUE TITLE
protect page and directory content

### ISSUE THREAD

**Issue by josefstr** [getgrav/grav-plugin-login#45]
I have a page with login needed to access, is there a way to make the files in the directory also protected?
Let's have the following structure:
02.private/
├── default.md
└── protected.file.txt

I want to include the 'protected.file.txt' in default.md, but 'protected.file.txt' shouldn't be accesible for non-logged in users.

**Comment by flaviocopes** [comment]
Added as a "Protect a login-protected page media" option

**Comment by plavet** [comment]
I just tried this. the page is protected and there is a login form. once logged in
you can see protected media, mp3. picture, txt file etc. However, if you copy links to those
media files, you can access them directly, logged in or not you can access them.
How does "Protect a login-protected page media" works? I suppose tweaking .htaccess
to block this kind of linking might work. To sum up, from the original question 

> I want to include the 'protected.file.txt' in default.md, but 'protected.file.txt' shouldn't be accesible for non-logged in users.

even with "Protect a login-protected page media" enabled, non-logged in users can access
page protected media with direct link.

**Comment by josefstr** [comment]
I couldn't find the option "Protect a login-protected page media",  so I could test it, too. Could you point me to this option?

**Comment by plavet** [comment]
Yes you just go to plugins page, it's Login v2.0.0, just click on the name and you are then on the plugins setup page, scroll to bottom and you can enable it there. I dont know maybe am doing something wrong :)

**Comment by josefstr** [comment]
thanks for pointing me to this option, just enabling the option doesn't protect any page content. Perhaps we are missing some other option we have to set.

**Comment by flaviocopes** [comment]
It's "Protect a login-protected page media" in the plugin configuration.

The page media is protected when accessed through the page route, as in `site.com/yourpage/yourmedia.mp3`

**Comment by plavet** [comment]
Yes that is what I am talking about, to recreate:
create a page, name it for example Download, in Frontmatter add
```
title: Download
access:
    site.login: true
```
In plugin settings enable "Protect a login-protected page media",
now go back to that page, "Download" for example, and add some media,
mp3, txt, jpg, then save, open the page, it will ask you to login. After login
you can access the page and see those media files, now copy the link adress
of either media file, for example `site.com/yourpage/yourmedia.mp3`,
then log out, paste that link in adress bar and it will give you access to that file,
or you don't have to log out just open another browser and paste that direct
link to the file and you can access it, logged in or not. The files are in correct place
```
02.download
├── default.md
└── protected.file.txt
└── protected.mp3
└── protected.jpg
```
So what am asking is, is that normal behavior of the Login plugin with 
"Protect a login-protected page media" enabled? or am I doing something wrong?

**Comment by josefstr** [comment]
This issue is marked as closed, but as there is no comment if this issue is solved or not I'd like to know what's the current status on it. Thanks.

**Comment by rhukster** [comment]
See Flavio's comment: https://github.com/getgrav/grav-plugin-login/issues/45#issuecomment-226834430

**Comment by josefstr** [comment]
and the behaviour of " plavet commented on 1 Aug " couldn't be reproduced on your side?

**Comment by codesplain** [comment]
Just had the same issue, fixed it by defining a route e.g. `route: /login` in `login.yaml`

**Comment by Dean-kasail** [comment]
i am able to access files with a direct link e.g /user/pages/09.folder/02.folder/_modular/somefile.pdf

**Comment by complanar** [comment]
It does not work at all, if you know the path of the file system. Only if you try to access via the route. 

Problem: Linking media via `|url` twig filter creates a path which includes the full physical path e.g.`/user/pages/01.foo/02.bar/file.txt`

Anyone can find out the numbers prefixing the directories by trial an error. You must define full custom routes for every page to prevent that and this is only security by obfuscation.

Plugin version: 3.9.6

**Comment by rhukster** [comment]
Coming back to this one properly, because several of you have reported the same thing over the years and the answer we gave in 2016 wasn't complete.

@complanar is right, and so was @Dean-kasail back in 2018. I tested this on the current release and confirmed it: with the option switched on, asking for a protected page's file through the page route correctly returns a 403, but asking for the same file at its actual location under `user/pages` serves it to anyone. The option makes no difference to that second case, and it never could.

Here's why, plainly. Your pages live in a folder that your web server can see. When someone asks for a file that's genuinely sitting there, Apache or nginx hands it straight over, so Grav is never started and no plugin gets a chance to check anything. That's not a hole we can patch in the Login plugin, it's how files in a web folder work. And as @complanar points out, you don't even need to guess the folder numbers, because Grav's own media links already use that path.

So what this option actually does is narrower than its description said: it applies the page's access rules when media is requested through the page's address. That's genuinely useful, but it is not the guarantee the setting's help text promised. I've reworded that text, because it's the reason this keeps getting reported as a bypass. People reasonably believed it did more.

What we're doing about it:

- Fixing a real bug alongside this: media inside a modular subfolder wasn't being checked at all, even through the page route. That's tracked in #294 and the fix is on `develop` now.
- Correcting the setting's description so it says what it does and what it doesn't.
- The bigger piece, an optional mode where page media is served only through Grav rather than directly off disk, belongs on Grav core rather than here. That's the only thing that would make this setting mean what people expect.

In the meantime, the honest advice: don't store files as page media if a stranger finding them would be a problem. Protecting the page protects what's written on it, not the folder it lives in.

Thanks to everyone who kept flagging this. You were describing something real and we should have said so more clearly the first time.

**Comment by rhukster** [comment]
Following up on the third point: the core side is now in, on Grav's `develop` (getgrav/grav@e3707c8d6, shipping in 2.0.25).

There's a new `pages.media_route_urls` setting. With it on, a page's media is linked by its page route rather than its path on disk, so the request goes through Grav and the `access` rules actually get applied. Resized images keep serving straight from the image cache, so nothing slows down.

That on its own hides the on-disk path rather than blocking it. What blocks it is denying `user/pages` at the web server, so every shipped config (.htaccess, nginx, Caddy, lighttpd, IIS) now carries that rule commented out, next to a warning that it must not be switched on unless `pages.media_route_urls` is on first. Enable the deny on its own and every media URL on the site becomes a 403.

Both are off by default, so nothing changes for an existing site until you opt in. Verified end to end: with both on, a protected page's file returns 403 whether it's asked for by route or by its real path, media in a modular subfolder included, while an ordinary page's media and resized images carry on serving normally.

**Comment by complanar** [comment]
Thank you very much! This was the feature I was looking for in the first place. 

> Following up on the third point: the core side is now in, on Grav's `develop` ([getgrav/grav@e3707c8d6](https://github.com/getgrav/grav/commit/e3707c8d6), shipping in 2.0.25).
> 
> There's a new `pages.media_route_urls` setting. With it on, a page's media is linked by its page route rather than its path on disk, so the request goes through Grav and the `access` rules actually get applied. Resized images keep serving straight from the image cache, so nothing slows down.
> 
> That on its own hides the on-disk path rather than blocking it. What blocks it is denying `user/pages` at the web server, so every shipped config (.htaccess, nginx, Caddy, lighttpd, IIS) now carries that rule commented out, next to a warning that it must not be switched on unless `pages.media_route_urls` is on first. Enable the deny on its own and every media URL on the site becomes a 403.
> 
> Both are off by default, so nothing changes for an existing site until you opt in. Verified end to end: with both on, a protected page's file returns 403 whether it's asked for by route or by its real path, media in a modular subfolder included, while an ordinary page's media and resized images carry on serving normally.
